services:
  master_postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - bmstu_docker_pg_data:/var/lib/postgresql/data
      - bmstu_docker_pg_ts:/var/lib/postgresql/tablespaces

volumes:
  bmstu_docker_pg_data:
    external: true
  bmstu_docker_pg_ts:
    external: true
